### ISSUE TITLE
rqlite multi-platform support

### ISSUE THREAD

**Issue by NerdyShawn** [rqlite/helm-charts#24]
Today [multi-platform is supported in the dockerhub image](https://hub.docker.com/r/rqlite/rqlite/tags) via rqlite image v8.24.9
![image](https://github.com/rqlite/helm-charts/assets/16088118/423773ba-37eb-4985-9136-20e3a0a5facf)

This issue is to track backing out the amd64 affinity applied prior via #13 to avoid  some issues that should be resolved now for users running qrlite on multiple cpu architectures.

**Comment by jtackaberry** [comment]
In 1.9.0.  Rather than reverting #13 entirely I just added the supported architectures to the node affinity list, because the original reasoning to include the node affinity in the first place still applies to other (unsupported) architectures.
